import { Activity, FileText, TrendingUp } from 'lucide-react'

const reportRows = [
  { name: 'Daily Sales Report', period: '22 Apr 2026', generatedBy: 'System', format: 'PDF' },
  { name: 'Inventory Aging Report', period: 'Weekly', generatedBy: 'Admin', format: 'XLSX' },
  { name: 'Franchise Outstanding Report', period: 'Monthly', generatedBy: 'System', format: 'PDF' },
]

export default function ReportsPage() {
  return (
    <section className="space-y-3">
      <div className="grid gap-2 sm:grid-cols-3">
        {[
          ['Reports Generated Today', '18', FileText],
          ['Scheduled Reports', '9', Activity],
          ['Growth Snapshot', '+14.8%', TrendingUp],
        ].map(([label, value, Icon]) => (
          <article key={label} className="rounded-lg border border-slate-200 bg-white p-3">
            <Icon size={16} className="text-[#008C95]" />
            <p className="mt-2 text-2xl font-semibold text-slate-900">{value}</p>
            <p className="text-sm text-slate-500">{label}</p>
          </article>
        ))}
      </div>
      <article className="rounded-lg border border-slate-200 bg-white p-3">
        <h2 className="text-lg font-semibold text-slate-900">Reports Center</h2>
        <div className="mt-3 overflow-x-auto">
          <table className="w-full min-w-[700px] text-left text-sm">
            <thead>
              <tr className="border-b border-slate-100 text-slate-500">
                <th className="px-3 py-3 font-medium">Report Name</th>
                <th className="px-3 py-3 font-medium">Period</th>
                <th className="px-3 py-3 font-medium">Generated By</th>
                <th className="px-3 py-3 font-medium">Format</th>
              </tr>
            </thead>
            <tbody>
              {reportRows.map((row) => (
                <tr key={row.name} className="border-b border-slate-100">
                  <td className="px-3 py-3">{row.name}</td>
                  <td className="px-3 py-3">{row.period}</td>
                  <td className="px-3 py-3">{row.generatedBy}</td>
                  <td className="px-3 py-3">{row.format}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </article>
    </section>
  )
}
